services:

  prunemate:
    image: anoniemerd/prunemate:latest
    container_name: prunemate
    ports:
      - "8200:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./logs:/var/log
      - ./config:/config
    environment:
      - PRUNEMATE_TZ=Europe/Madrid
      - PRUNEMATE_TIME_24H=true
    restart: unless-stopped